const express = require('express');
const path = require('path'); // NEW

const app = express();
const port = process.env.PORT || 3000;
const DIST_DIR = path.join(__dirname, '../dist');
const HTML_FILE = path.join(DIST_DIR, 'index.html');

const mockResponse = {
  foo: 'bar',
  bar: 'foo'
};

app.use(express.static(DIST_DIR));

app.get('/api', (req, res) => {
  res.send(mockResponse);
});

app.get('/', (req, res) => {
 res.sendFile(HTML_FILE); 
}); // Now, "/" route returns el html file generated by webpack into dist folder. It uses the middleware function use.static

app.listen(port, function () {
 console.log('App listening on port: ' + port);
});

/* const express = require('express');
const app = express();
const port = process.env.PORT || 3000;
const mockResponse = {
  foo: 'bar',
  bar: 'foo'
};
app.get('/api', (req, res) => {
  res.send(mockResponse);
});

app.get('/', (req, res, next) => {
  console.log(Date.now());
  next()
 },
 (req, res) => {
  res.status(200).send('Hello World!');
 });


app.listen(port, function () {
 console.log('App listening on port: ' + port);
}); */